services:
  elasticsearch:
    container_name: es01
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=pass_me
      - "ES_JAVA_OPTS=-Xms4096m -Xmx6000m"
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
    network_mode: host
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: "65536"
        hard: "65536"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    restart: always
    network_mode: host
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=pass_me