version: '3'
services:
  mysql:
    image: bitnami/mysql:5.7
    network_mode: host
    restart: always
    volumes:
       - ./mysql-data:/bitnami/mysql/data
       - ./my.cnf:/opt/bitnami/mysql/conf/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./data:/bitnami/mariadb
      - ./my.cnf:/opt/bitnami/mariadb/conf/my.cnf
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "3"
#     networks:
#       - dockernet
# networks:
#   dockernet:
#     external: true